### PR TITLE
Use AI streaming in tutorial

### PR DESCRIPTION
**Pull request by petersalas**

### CODE REVIEW

**Review by mdwelsh — APPROVED** [review]
I think it's a lot harder to follow this way, i.e., the actual prompt is stuffed into the default of the `useState` call, etc.) but whatever -- we can make it simpler. Is the AI stream thingy checked in?

**Comment by mdwelsh** [comment]
@petersalas Can you do a `vercel deploy` on this so I can see it live?

**Comment by petersalas** [comment]
@mdwelsh when I run `vercel deploy` it barfs

**Comment by petersalas** [comment]
@mdwelsh re:
> I think it's a lot harder to follow this way, i.e., the actual prompt is stuffed into the default of the useState call, etc.) but whatever -- we can make it simpler. Is the AI stream thingy checked in?

If we want to optimize for simplicity there's nothing better than #4. But the problem is that one can't build anything interactive with it, so I think it's actually pretty important to show how you're expected to deal with interactivity.

**Comment by petersalas** [comment]
Gonna merge because I can't figure out how to `vercel deploy` -- we can take stuff out as we see fit.

**Pull request merged**
